apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummysite
resources:
  - namespace.yaml
  - resourcedefinition.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - dummysite.yaml
