apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-ping-pong-claim
spec:
  storageClassName: log-ping-pong-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi