apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-with-kubernetes-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-with-kubernetes-project
  template:
    metadata:
      labels:
        app: devops-with-kubernetes-project
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: the-project-claim
      containers:
        - name: devops-with-kubernetes-frontend
          image: eetujukka/devops-with-kubernetes-frontend:1.2
          volumeMounts:
            - name: image-volume
              mountPath: /usr/src/app/files
        - name: devops-with-kubernetes-backend
          image: eetujukka/devops-with-kubernetes-backend:1.1
          env:
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: image-volume
              mountPath: /usr/src/app/files
