apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backendconfig.yaml
- broadcaster-deployment.yaml
- configmap.yaml
- deployment.yaml
- ingress.yaml
- jobs/pg-dump.yaml
- namespace.yaml
- pvc.yaml
- service.yaml
images:
- name: eetujukka/devops-with-kubernetes-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-backend
  newTag: c7ae42964a3d7a3d3baa4fc316f9a731d3e49577
- name: eetujukka/devops-with-kubernetes-frontend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-frontend
  newTag: c7ae42964a3d7a3d3baa4fc316f9a731d3e49577
