apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backendconfig.yaml
- broadcaster-deployment.yaml
- configmap.yaml
- deployment.yaml
- ingress.yaml
- jobs/pg-dump.yaml
- namespace.yaml
- pvc.yaml
- service.yaml
images:
- name: eetujukka/devops-with-kubernetes-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-backend
  newTag: 6638a09b47e192da350fdfe130861862937ffef3
- name: eetujukka/devops-with-kubernetes-frontend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-frontend
  newTag: 6638a09b47e192da350fdfe130861862937ffef3
