apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-project-v2-claim
  namespace: the-project
spec:
  storageClassName: the-project-v2-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi