apiVersion: v1
kind: Secret
metadata:
    name: project-postgres-password
    namespace: logger
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0oK+Po1wz5R10uBt,iv:jL+QlKkCQ2M57bSAwChFiKCIEUZvHu+2aah1q/AelFs=,tag:XAViTk+sSxD9UVwfSOTeXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM1JaVTV0YTZadjdTMnpB
            ekdlZndVTFhNTm96Zm96Tm04OWtTODhKT3prCjNUejcyQ2JsTFNtNVMzKzFGcnY3
            Q1RUUWljcmZydndjRytNUVZKSFNJak0KLS0tIEkwMFQzVGpxTnRNRkFaUUdFSUlE
            VDdqUTB0c0dYNzdLeW03QjFyc3pvYjQK0jjgNfEzuMmySborjUWG8s8HakTwRXzp
            7cQU4PmeQAtHr5L1ZrtmkX8ZxLUK3IWuFBd0HOEH2f9oT1wSo2lYxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqu95crk3gvwvdwz33786z3xyvhxfuygtes4kl465zrqvhlc639qn5g7mg
    encrypted_regex: ^(data)$
    lastmodified: "2026-07-19T15:11:47Z"
    mac: ENC[AES256_GCM,data:yUezbSiS2FE0Q0i1JZswgMKGlF5h4GdesiFp1ge7b+upSn6HuQilYheNxw5iIZw76Bq0yCU/qIMIUBTpNMuLwKOCpFQwdAgmcbf58zzYfCJtLQR1/9B1ZLdXODx+8iHDY+/Hq7Xh+KUaWPbkVpq8PzgOZn7qwNEHPtfkiGivgY8=,iv:YaQB/NjW+/eVmpl5e/PribvBl9VVt1jBQrS/hDoCtWg=,tag:LM9LGlfRujXsxy989thnug==,type:str]
    version: 3.13.2
