apiVersion: v1
kind: Service
metadata:
  name: devops-with-kubernetes-project-svc
spec:
  type: ClusterIP
  selector:
    app: devops-with-kubernetes-project
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3001