apiVersion: v1
kind: Secret
metadata:
    name: pingpong-postgres-password
    namespace: logger
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0NhqZ7ajTtl2SqpD,iv:wi1OjiJj4xyt+AWOccpbNMMxUsb+FKxhg/THj2+VczE=,tag:WCMD2kDhq+ZDdRUllaBeYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZUtadG1sbXRER3RmYzU3
            cmpBVHBZRFpYM1VnOVREakhvekdiUElYRndFClppMEIybGtZTWo5ZEluYk4wMmNP
            Y0RyWmRSZitNcDRpSkNMR3NHVGlGZWMKLS0tIDBjSzlnZWc1THQ5aFA5blZkNEQv
            cm02cS95cjdEY21qdzZVdkViMUI3VFkKc5ghQod1FuULXFEC4aa6J5lGxITYYqNG
            doOOBvm91KgaLNZ8gMWmCzTOufgEr8pjCuojJLWgTCBckpiCW/+fdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tqu95crk3gvwvdwz33786z3xyvhxfuygtes4kl465zrqvhlc639qn5g7mg
    encrypted_regex: ^(data)$
    lastmodified: "2026-07-19T11:59:42Z"
    mac: ENC[AES256_GCM,data:yaRTWwajWRxYxFQod31Ti0P119jv2ByDvLd5jrG0/2D9SOGrG+/2FPAQ1O91s6JP1WzgEjDZxt0WqgHWJw/G3/tz2SG7yovmVwH75KzHTngapQJDRJM72rZEKXoSDJ+GzzaFZLfJqcmxnoqMsGX/4qasV5URi6e09fA24Y+exsc=,iv:xTIf1oaKRgHOGKB8ARAbJsbl744IXxuttns0nWaZw1g=,tag:6YSNKaf0on0j9hKtv5W/vw==,type:str]
    version: 3.13.2
