apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logger-ingress
  namespace: logger
spec:
  rules:
    - http:
        paths:
          - path: /log-output
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 2345
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: pingpong-svc
                port:
                  number: 6789
