apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logger
resources:
- gateway.yaml
- log-output-configmap.yaml
- log-output-deployment.yaml
- log-output-route.yaml
- log-output-service.yaml
- namespace.yaml
- pingpong-analysis.yaml
- pingpong-deployment.yaml
- pingpong-route.yaml
- pingpong-service.yaml
- pv.yaml
- pvc.yaml
images:
- name: eetujukka/log-output-logger
  newName: eetujukka/log-output-logger
  newTag: 473b99e491f17c8695ecd50082f7640aa7ca35d3
- name: eetujukka/log-output-server
  newName: eetujukka/log-output-server
  newTag: 473b99e491f17c8695ecd50082f7640aa7ca35d3
- name: eetujukka/pingpong
  newName: eetujukka/pingpong
  newTag: 473b99e491f17c8695ecd50082f7640aa7ca35d3
