apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logger
resources:
- greeting-service-deployment.yaml
- greeting-service-routing.yaml
- greeting-service-service.yaml
- gateway.yaml
- log-output-configmap.yaml
- log-output-deployment.yaml
- log-output-service.yaml
- namespace.yaml
- pingpong-analysis.yaml
- pingpong-deployment.yaml
- pingpong-service.yaml
- pv.yaml
- pvc.yaml
- waypoint.yaml
images:
- name: eetujukka/greeting-service
  newName: eetujukka/greeting-service
  newTag: 0f779100e54c09cbc7003b0b14e9d01555d2a896
- name: eetujukka/log-output-logger
  newName: eetujukka/log-output-logger
  newTag: 0f779100e54c09cbc7003b0b14e9d01555d2a896
- name: eetujukka/log-output-server
  newName: eetujukka/log-output-server
  newTag: 0f779100e54c09cbc7003b0b14e9d01555d2a896
- name: eetujukka/pingpong
  newName: eetujukka/pingpong
  newTag: 0f779100e54c09cbc7003b0b14e9d01555d2a896
