apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logger
resources:
- gateway.yaml
- log-output-configmap.yaml
- log-output-deployment.yaml
- log-output-service.yaml
- namespace.yaml
- pingpong-analysis.yaml
- pingpong-deployment.yaml
- pingpong-service.yaml
- pv.yaml
- pvc.yaml
images:
- name: eetujukka/log-output-logger
  newName: eetujukka/log-output-logger
  newTag: a54706d0c5b7d1d9812dd0f296e4fea94b5366a9
- name: eetujukka/log-output-server
  newName: eetujukka/log-output-server
  newTag: a54706d0c5b7d1d9812dd0f296e4fea94b5366a9
- name: eetujukka/pingpong
  newName: eetujukka/pingpong
  newTag: a54706d0c5b7d1d9812dd0f296e4fea94b5366a9
